name: Terraform Plan and Apply with Terragrunt

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  terragrunt:
    runs-on: ubuntu-latest  # The runner that will execute the steps

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up AWS Credentials (authentication with AWS)
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Install Terragrunt and other dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -LO https://github.com/gruntwork-io/terragrunt/releases/download/v0.45.8/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      # Step 4: Set environment variable based on the branch (for dev or prod)
      - name: Set environment variable
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "TARGET_ENV=prod" >> $GITHUB_ENV
          else
            echo "TARGET_ENV=dev" >> $GITHUB_ENV
          fi

      # Step 5: Run Terragrunt in the appropriate environment folder
      - name: Run Terragrunt Apply
        working-directory: ./terragrunt/envs/${{ env.TARGET_ENV }}
        run: |
          terragrunt init
          terragrunt apply -auto-approve
